### ISSUE TITLE
TypeError: stream.on is not a function

### ISSUE THREAD

**Issue by ambroiseRabier** [cucumber/cucumber-electron#59]
I have the following error when I try to start cucumber-electron with minimum setup.

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run cucumber --scripts-prepend-node-path=auto

> learn-tools@1.0.0 cucumber L:\PROJECTS_3\WEB\learn-tools
> cucumber-electron


The vm module of Node.js is deprecated in the renderer process and will be removed.
TypeError: stream.on is not a function
    at L:\PROJECTS_3\WEB\learn-tools\node_modules\@cucumber\cucumber\src\cli\index.ts:117:16
    at tryCatcher (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (L:\PROJECTS_3\WEB\learn-tools\node_modules\bluebird\js\release\async.js:15:14)npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! learn-tools@1.0.0 cucumber: `cucumber-electron`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the learn-tools@1.0.0 cucumber script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AmbroiseRabier\AppData\Roaming\npm-cache\_logs\2021-04-28T11_03_45_779Z-debug.log

Process finished with exit code 3

```
https://github.com/cucumber/cucumber-js/blob/238947f9966369bf4987a3574fcf94332f2feb70/src/cli/index.ts#L117

Using:
```
    "@cucumber/cucumber": "^7.2.1",
    "@cucumber/electron": "^3.0.0",
    "electron": "12.0.4",
```

**Comment by romaingweb** [comment]
@ambroiseRabier We are working on this issue. There is a compatibility issue between the most recent versions of cucumber-js and cucumber-electron. You can follow the progress here: https://github.com/cucumber/cucumber-electron/pull/60.

Thank you for reaching out to us.
